version: '3.8' 

services:
  db:
    image: postgres:latest 
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}           
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-db-admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}

  ecommerce-app:
    build: .
    container_name: ecommerce-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
  pgadmin_data:
